# Generated by Django 5.1.2 on 2024-10-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('article_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Article Number')),
                ('priority', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=[1])),
                ('visual_priority', models.IntegerField(choices=[(1, 'Зеленый'), (2, 'Желтый'), (3, 'Красный')], default=[3])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.city')),
            ],
            options={
                'ordering': ['-priority', 'visual_priority'],
            },
        ),
    ]
