# Generated by Django 5.1.2 on 2024-11-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disk', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_articul', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('full_title', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('diameter', models.CharField(max_length=100)),
                ('pcd', models.CharField(max_length=100)),
                ('boltcount', models.CharField(max_length=100)),
                ('outfit', models.CharField(max_length=100)),
                ('dia', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TruckDiskSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('input_price', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('presence', models.CharField(max_length=100)),
                ('delivery_period_days', models.IntegerField()),
                ('last_availability_date', models.DateTimeField()),
                ('sale', models.CharField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.city')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                ('truck_disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.truckdisk')),
            ],
        ),
    ]
