# Generated by Django 5.1.2 on 2024-11-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_description_order_company_protector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='protector',
            field=models.CharField(blank=True, choices=[('all_season', 'Всесезонный'), ('summer', 'Лето'), ('winter', 'Зима'), ('winter_spikes', 'Зима/Шипы')], max_length=20, null=True),
        ),
    ]
