# Generated by Django 5.1.2 on 2024-11-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_protector'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ad_order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
